### ISSUE TITLE
Handlebars template of html

### ISSUE THREAD

**Issue by Goosetaculous** [novialim/farmily#33] opened 2017-07-29 21:01 UTC
Analyze the html pages and determine a handlebar template layout

**Comment by jhuynh85** [comment] 2017-07-29 23:18
Handlebars files and folders added in PR #40. The module still needs to be loaded in `server.js`

**Comment by jhuynh85** [comment] 2017-08-01 07:17
Dupe of #47, #48, #49

**Comment by jhuynh85** [comment] 2017-08-08 04:58
- [x] index
- [x] explore
- [x] addfarmer
- [x] allfarmer
- [ ] addreview
- [ ] contribute
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by jhuynh85** [comment] 2017-08-10 09:25
@novialim Are there any pages we're missing? I'm not up-to-date on which pages we want to convert to handlebars

**Comment by novialim** [comment] 2017-08-10 10:10
updated your comment and I will double check everything Friday evening. (WHEN WE STOP CODING!!)

**Closed** 2017-08-12 01:43 UTC
Labels: high priority
